# This file is part of PyImgur.

# PyImgur is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# PyImgur is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with PyImgur.  If not, see <http://www.gnu.org/licenses/>.

MOCKED_IMAGE_DATA = {
    "id": "JPz2i",
    "deletehash": "",
    "account_id": 326490,
    "account_url": None,
    "ad_type": None,
    "ad_url": None,
    "title": None,
    "description": None,
    "name": "logo",
    "type": "image/png",
    "width": 205,
    "height": 78,
    "size": 16532,
    "views": 0,
    "section": None,
    "vote": None,
    "bandwidth": 0,
    "animated": False,
    "favorite": False,
    "in_gallery": False,
    "in_most_viral": False,
    "has_sound": False,
    "is_ad": False,
    "nsfw": None,
    "link": "https://i.imgur.com/JPz2i.png",
    "tags": [],
    "datetime": 1347889444,
    "mp4": "",
    "hls": "",
}
IMAGE_EXPECTED_DATA = {
    "_info_url": "https://api.imgur.com/3/image/JPz2i",
    "deletehash": "",
    "_has_fetched": True,
    "id": "JPz2i",
    "account_id": 326490,
    "account_url": None,
    "ad_type": None,
    "ad_url": None,
    "title": None,
    "description": None,
    "name": "logo",
    "type": "image/png",
    "width": 205,
    "height": 78,
    "size": 16532,
    "views": 0,
    "section": None,
    "vote": None,
    "bandwidth": 0,
    "in_gallery": False,
    "in_most_viral": False,
    "has_sound": False,
    "is_ad": False,
    "link": "https://i.imgur.com/JPz2i.png",
    "tags": [],
    "datetime": 1347889444,
    "mp4": "",
    "hls": "",
    "is_favorited": False,
    "is_nsfw": None,
    "is_animated": False,
    "link_small_square": "https://i.imgur.com/JPz2is.png",
    "link_big_square": "https://i.imgur.com/JPz2ib.png",
    "link_small_thumbnail": "https://i.imgur.com/JPz2it.png",
    "link_medium_thumbnail": "https://i.imgur.com/JPz2im.png",
    "link_large_thumbnail": "https://i.imgur.com/JPz2il.png",
    "link_huge_thumbnail": "https://i.imgur.com/JPz2ih.png",
}

MOCKED_ALBUM_DATA = {
    "id": "PaUermF",
    "title": "Scoots and the shoe",
    "description": "",
    "datetime": 1741742409,
    "cover": "",
    "cover_width": 0,
    "cover_height": 0,
    "account_url": "KittensForDays",
    "account_id": 71846935,
    "privacy": "private",
    "layout": "blog",
    "views": 37155,
    "link": "https://imgur.com/a/PaUermF",
    "favorite": True,
    "nsfw": None,
    "section": "",
    "images": [
        {
            "id": "kogeU9H",
            "deletehash": "",
            "account_id": 71846935,
            "account_url": None,
            "ad_type": None,
            "ad_url": None,
            "title": None,
            "description": "Scooty Booty has taken a shine to my tennis shoes. I went to put them on today to work out and the laces had all been pulled apart. Now I know why!! What an adorable little weirdo.",  # pylint: disable=line-too-long
            "name": "",
            "type": "video/mp4",
            "width": 854,
            "height": 480,
            "size": 0,
            "views": 0,
            "section": None,
            "vote": None,
            "bandwidth": 0,
            "animated": True,
            "favorite": False,
            "in_gallery": True,
            "in_most_viral": False,
            "has_sound": True,
            "is_ad": False,
            "nsfw": None,
            "link": "https://i.imgur.com/kogeU9H.mp4",
            "tags": [],
            "mp4_size": 15106767,
            "processing": {"status": "completed"},
            "datetime": 1741742398,
            "mp4": "https://i.imgur.com/kogeU9H.mp4",
            "hls": "",
        },
        {
            "id": "ajHaSG9",
            "deletehash": "",
            "account_id": 71846935,
            "account_url": None,
            "ad_type": None,
            "ad_url": None,
            "title": None,
            "description": "I don’t think it fits, Scoots.",
            "name": "",
            "type": "image/jpeg",
            "width": 2048,
            "height": 1536,
            "size": 1299803,
            "views": 0,
            "section": None,
            "vote": None,
            "bandwidth": 0,
            "animated": False,
            "favorite": False,
            "in_gallery": True,
            "in_most_viral": False,
            "has_sound": False,
            "is_ad": False,
            "nsfw": None,
            "link": "https://i.imgur.com/ajHaSG9.jpeg",
            "tags": [],
            "datetime": 1741742325,
            "mp4": "",
            "hls": "",
        },
    ],
    "ad_config": {
        "show_ads": True,
        "show_ad_level": 2,
        "ad_sense_client_id": "pub-3159527443924881",
        "nsfw_score": 0,
        "safe_flags": ["in_gallery", "album", "page_load"],
        "high_risk_flags": [],
        "unsafe_flags": [],
        "wall_unsafe_flags": [],
    },
    "images_count": 2,
    "in_gallery": True,
    "is_ad": False,
    "include_album_ads": False,
    "is_album": True,
}
ALBUM_EXPECTED_DATA = {
    "_info_url": "https://api.imgur.com/3/album/PaUermF",
    "deletehash": None,
    "_has_fetched": True,
    "id": "PaUermF",
    "title": "Scoots and the shoe",
    "description": "",
    "datetime": 1741742409,
    "cover_width": 0,
    "cover_height": 0,
    "account_id": 71846935,
    "privacy": "private",
    "layout": "blog",
    "views": 37155,
    "link": "https://imgur.com/a/PaUermF",
    "section": "",
    "ad_config": {
        "show_ads": True,
        "show_ad_level": 2,
        "ad_sense_client_id": "pub-3159527443924881",
        "nsfw_score": 0,
        "safe_flags": ["in_gallery", "album", "page_load"],
        "high_risk_flags": [],
        "unsafe_flags": [],
        "wall_unsafe_flags": [],
    },
    "in_gallery": True,
    "is_ad": False,
    "include_album_ads": False,
    "is_album": True,
    "is_favorited": True,
    "is_nsfw": None,
}

MOCKED_GALLERY_ALBUM_DATA = {
    "id": "vDtsSUW",
    "title": "Baby elephant asks for water from a man in Nepal",
    "description": None,
    "datetime": 1741712827,
    "cover": "TGE2lL4",
    "cover_width": 480,
    "cover_height": 854,
    "account_url": "tampacl",
    "account_id": 28352345,
    "privacy": "hidden",
    "layout": "blog",
    "views": 55119,
    "link": "https://imgur.com/a/vDtsSUW",
    "ups": 2398,
    "downs": 23,
    "points": 2375,
    "score": 2402,
    "is_album": True,
    "vote": None,
    "favorite": False,
    "nsfw": False,
    "section": "",
    "comment_count": 65,
    "favorite_count": 334,
    "topic": None,
    "topic_id": None,
    "images_count": 1,
    "in_gallery": True,
    "is_ad": False,
    "tags": [
        {
            "name": "elephant",
            "display_name": "elephant",
            "followers": 7957,
            "total_items": 2695,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "qaYq4fG",
            "thumbnail_hash": None,
            "accent": "51535A",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "aww",
            "display_name": "Aww",
            "followers": 3754471,
            "total_items": 606687,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "avRBRpN",
            "thumbnail_hash": "avRBRpN",
            "accent": "60AEBB",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "The cutest and most adorable things on the internet",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "cute",
            "display_name": "Cute",
            "followers": 171630,
            "total_items": 210434,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "MifWJps",
            "thumbnail_hash": None,
            "accent": "3BA3B1",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "funny",
            "display_name": "Funny",
            "followers": 6792185,
            "total_items": 2174334,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "9r1qCDq",
            "thumbnail_hash": None,
            "accent": "633875",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "LOLs, ROFLs, LMAOs",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
    ],
    "ad_type": 0,
    "ad_url": "",
    "in_most_viral": True,
    "include_album_ads": False,
    "images": [
        {
            "id": "TGE2lL4",
            "title": None,
            "description": None,
            "datetime": 1741712812,
            "type": "video/mp4",
            "animated": True,
            "width": 480,
            "height": 854,
            "size": 12431289,
            "views": 800896,
            "bandwidth": 9956169634944,
            "vote": None,
            "favorite": False,
            "nsfw": None,
            "section": None,
            "account_url": None,
            "account_id": None,
            "is_ad": False,
            "in_most_viral": False,
            "has_sound": False,
            "tags": [],
            "ad_type": 0,
            "ad_url": "",
            "edited": "0",
            "in_gallery": False,
            "link": "https://i.imgur.com/TGE2lL4.mp4",
            "mp4_size": 12431289,
            "mp4": "https://i.imgur.com/TGE2lL4.mp4",
            "gifv": "https://i.imgur.com/TGE2lL4.gifv",
            "hls": "https://i.imgur.com/TGE2lL4.m3u8",
            "processing": {"status": "completed"},
            "comment_count": None,
            "favorite_count": None,
            "ups": None,
            "downs": None,
            "points": None,
            "score": None,
        }
    ],
    "ad_config": {
        "safeFlags": ["album", "in_gallery", "gallery"],
        "highRiskFlags": [],
        "unsafeFlags": ["onsfw_mod_unsafe"],
        "wallUnsafeFlags": [],
        "showsAds": False,
        "showAdLevel": 1,
        "safe_flags": ["album", "in_gallery", "gallery"],
        "high_risk_flags": [],
        "unsafe_flags": ["onsfw_mod_unsafe"],
        "wall_unsafe_flags": [],
        "show_ads": False,
        "show_ad_level": 1,
        "nsfw_score": 0.4,
    },
}
GALLERY_ALBUM_EXPECTED_DATA = {
    "_info_url": "https://api.imgur.com/3/album/vDtsSUW",
    "deletehash": None,
    "_has_fetched": True,
    "id": "vDtsSUW",
    "title": "Baby elephant asks for water from a man in Nepal",
    "description": None,
    "datetime": 1741712827,
    "cover_width": 480,
    "cover_height": 854,
    "account_id": 28352345,
    "privacy": "hidden",
    "layout": "blog",
    "views": 55119,
    "link": "https://imgur.com/a/vDtsSUW",
    "ups": 2398,
    "downs": 23,
    "points": 2375,
    "score": 2402,
    "is_album": True,
    "vote": None,
    "section": "",
    "comment_count": 65,
    "favorite_count": 334,
    "topic": None,
    "topic_id": None,
    "in_gallery": True,
    "is_ad": False,
    "tags": [
        {
            "name": "elephant",
            "display_name": "elephant",
            "followers": 7957,
            "total_items": 2695,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "qaYq4fG",
            "thumbnail_hash": None,
            "accent": "51535A",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "aww",
            "display_name": "Aww",
            "followers": 3754471,
            "total_items": 606687,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "avRBRpN",
            "thumbnail_hash": "avRBRpN",
            "accent": "60AEBB",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "The cutest and most adorable things on the internet",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "cute",
            "display_name": "Cute",
            "followers": 171630,
            "total_items": 210434,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "MifWJps",
            "thumbnail_hash": None,
            "accent": "3BA3B1",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
        {
            "name": "funny",
            "display_name": "Funny",
            "followers": 6792185,
            "total_items": 2174334,
            "following": False,
            "is_whitelisted": False,
            "background_hash": "9r1qCDq",
            "thumbnail_hash": None,
            "accent": "633875",
            "background_is_animated": False,
            "thumbnail_is_animated": False,
            "is_promoted": False,
            "description": "LOLs, ROFLs, LMAOs",
            "logo_hash": None,
            "logo_destination_url": None,
            "description_annotations": {},
        },
    ],
    "ad_type": 0,
    "ad_url": "",
    "in_most_viral": True,
    "include_album_ads": False,
    "ad_config": {
        "safeFlags": ["album", "in_gallery", "gallery"],
        "highRiskFlags": [],
        "unsafeFlags": ["onsfw_mod_unsafe"],
        "wallUnsafeFlags": [],
        "showsAds": False,
        "showAdLevel": 1,
        "safe_flags": ["album", "in_gallery", "gallery"],
        "high_risk_flags": [],
        "unsafe_flags": ["onsfw_mod_unsafe"],
        "wall_unsafe_flags": [],
        "show_ads": False,
        "show_ad_level": 1,
        "nsfw_score": 0.4,
    },
    "is_favorited": False,
    "is_nsfw": False,
}

MOCKED_GALLERY_IMAGE_DATA = {
    "id": "CleiK2V",
    "title": "MRW When I go to the bathroom without my smartphone...",
    "description": None,
    "datetime": 1374456562,
    "type": "image/gif",
    "animated": True,
    "width": 400,
    "height": 225,
    "size": 699340,
    "views": 21338,
    "bandwidth": 14922516920,
    "vote": None,
    "favorite": False,
    "nsfw": False,
    "section": "gifs",
    "account_url": "darthmonkey",
    "account_id": 718642,
    "is_ad": False,
    "in_most_viral": True,
    "has_sound": False,
    "tags": [],
    "ad_type": 0,
    "ad_url": "",
    "edited": 0,
    "in_gallery": True,
    "topic": None,
    "topic_id": 0,
    "link": "https://i.imgur.com/CleiK2V.gif",
    "mp4": "https://i.imgur.com/CleiK2V.mp4",
    "gifv": "https://i.imgur.com/CleiK2V.gifv",
    "hls": "https://i.imgur.com/CleiK2V.m3u8",
    "mp4_size": 68779,
    "looping": True,
    "ad_config": {
        "safeFlags": ["in_gallery", "page_load"],
        "highRiskFlags": [],
        "unsafeFlags": [],
        "wallUnsafeFlags": [],
        "showsAds": True,
        "showAdLevel": 2,
        "safe_flags": ["in_gallery", "page_load"],
        "high_risk_flags": [],
        "unsafe_flags": [],
        "wall_unsafe_flags": [],
        "show_ads": True,
        "show_ad_level": 2,
        "nsfw_score": 0,
    },
    "comment_count": 150,
    "favorite_count": 837,
    "ups": 6378,
    "downs": 139,
    "points": 6239,
    "score": 6249,
    "is_album": False,
}
GALLERY_IMAGE_EXPECTED_DATA = {
    "_info_url": "https://api.imgur.com/3/image/CleiK2V",
    "deletehash": None,
    "_has_fetched": True,
    "id": "CleiK2V",
    "title": "MRW When I go to the bathroom without my smartphone...",
    "description": None,
    "datetime": 1374456562,
    "type": "image/gif",
    "width": 400,
    "height": 225,
    "size": 699340,
    "views": 21338,
    "bandwidth": 14922516920,
    "vote": None,
    "section": "gifs",
    "account_id": 718642,
    "is_ad": False,
    "in_most_viral": True,
    "has_sound": False,
    "tags": [],
    "ad_type": 0,
    "ad_url": "",
    "edited": 0,
    "in_gallery": True,
    "topic": None,
    "topic_id": 0,
    "link": "https://i.imgur.com/CleiK2V.gif",
    "mp4": "https://i.imgur.com/CleiK2V.mp4",
    "gifv": "https://i.imgur.com/CleiK2V.gifv",
    "hls": "https://i.imgur.com/CleiK2V.m3u8",
    "mp4_size": 68779,
    "looping": True,
    "ad_config": {
        "safeFlags": ["in_gallery", "page_load"],
        "highRiskFlags": [],
        "unsafeFlags": [],
        "wallUnsafeFlags": [],
        "showsAds": True,
        "showAdLevel": 2,
        "safe_flags": ["in_gallery", "page_load"],
        "high_risk_flags": [],
        "unsafe_flags": [],
        "wall_unsafe_flags": [],
        "show_ads": True,
        "show_ad_level": 2,
        "nsfw_score": 0,
    },
    "comment_count": 150,
    "favorite_count": 837,
    "ups": 6378,
    "downs": 139,
    "points": 6239,
    "score": 6249,
    "is_album": False,
    "is_favorited": False,
    "is_nsfw": False,
    "is_animated": True,
    "link_small_square": "https://i.imgur.com/CleiK2Vs.gif",
    "link_big_square": "https://i.imgur.com/CleiK2Vb.gif",
    "link_small_thumbnail": "https://i.imgur.com/CleiK2Vt.gif",
    "link_medium_thumbnail": "https://i.imgur.com/CleiK2Vm.gif",
    "link_large_thumbnail": "https://i.imgur.com/CleiK2Vl.gif",
    "link_huge_thumbnail": "https://i.imgur.com/CleiK2Vh.gif",
}

MOCKED_COMMENT_DATA = {
    "id": 49538390,
    "image_id": "LA2RQqp",
    "comment": "I think you're right.",
    "author": "hauster1",
    "author_id": 2543901,
    "on_album": False,
    "album_cover": None,
    "ups": 1226,
    "downs": 13,
    "points": 1213,
    "datetime": 1367270516,
    "parent_id": 0,
    "deleted": False,
    "vote": None,
    "platform": "unknown",
    "has_admin_badge": False,
    "children": [],
}
COMMENT_EXPECTED_DATA = {
    "deletehash": None,
    "_info_url": "https://api.imgur.com/3/comment/49538390",
    "_has_fetched": True,
    "id": 49538390,
    "on_album": False,
    "album_cover": None,
    "ups": 1226,
    "downs": 13,
    "points": 1213,
    "datetime": 1367270516,
    "vote": None,
    "platform": "unknown",
    "has_admin_badge": False,
    "replies": [],
    "text": "I think you're right.",
    "is_deleted": False,
    "permalink": "http://imgur.com/gallery/LA2RQqp/comment/49538390",
    "parent": None,
}

MOCKED_USER_DATA = {
    "id": 718642,
    "url": "darthmonkey",
    "bio": "I saw a duck once.",
    "avatar": "https://imgur.com/user/darthmonkey/avatar?maxwidth=290",
    "avatar_name": "default/D",
    "cover": "https://imgur.com/user/darthmonkey/cover?maxwidth=2560",
    "cover_name": "default/1-space",
    "reputation": 26921,
    "reputation_name": "Glorious",
    "created": 1327824060,
    "pro_expiration": False,
    "user_follow": {"status": False, "type": 0},
    "is_blocked": False,
}
USER_EXPECTED_DATA = {
    "_info_url": "https://api.imgur.com/3/account/darthmonkey",
    "_has_fetched": True,
    "id": 718642,
    "bio": "I saw a duck once.",
    "avatar": "https://imgur.com/user/darthmonkey/avatar?maxwidth=290",
    "avatar_name": "default/D",
    "cover": "https://imgur.com/user/darthmonkey/cover?maxwidth=2560",
    "cover_name": "default/1-space",
    "reputation": 26921,
    "reputation_name": "Glorious",
    "created": 1327824060,
    "pro_expiration": False,
    "user_follow": {"status": False, "type": 0},
    "is_blocked": False,
    "name": "darthmonkey",
}